# Generated by Django 5.0.3 on 2024-03-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('normal bikes', 1), ('sports', 2), ('parts', 3)], max_length=50, verbose_name='Category'),
        ),
    ]
